apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: my-app-monitor
  labels:
    release: prometheus # This label must match the selector in your Prometheus resource
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-learning
  podMetricsEndpoints:
  - port: http # Matches the "http" containerPort name in the Deployment
    path: /metrics
