apiVersion: v1
kind: Service
metadata:
  name: kube-learning
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kube-learning
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
